- package/sysupgrade-image-server/Makefile
dependency on python3-distutils was masked by inaccurate packaging of
python-yaml. Now that python-yaml is packaged more tightly it blew up.
> update server package dependencies

- package/sysupgrade-image-server/Makefile
python-openssl was masked by python-yaml pulling in python3
python-gnupg wasn't previously used
> add python-openssl and python-gnupg dependency

- distributions/lede/distro_config.yml
- distributions/openwrt/distro_config.yml
If I understand well, This is what would be needed to have WRT3200ACM working, fixing https://github.com/aparcar/attendedsysupgrade-server/issues/129
> Manually map armada-385-linksys-rango -> linksys-wrt3200acm

- asu/utils/distributions/lime/distro_config.yml
- asu/utils/distributions/openwrt/distro_config.yml
'mvevu' -> 'mvebu'
Fixes: issue #165 introduced by commit 4667913 "distributions: add common targets"
> distributions: fix typo in targets

- README.md
- asu/request.py
- asu/utils/updater.py
there was a time when target and subtarget were stored sepparated,
however it's now stored together.
> cleanup: "subtarget" separation

- Dockerfile
This is required to use psql from the server/worker image.
> Dockerfile: install postgresql-client

- .gitlab-ci.yml
The image isn't build on the deploy step, therefore pull it.
> CI: fixup docker deploy via pull

- README.md
> CI: readme replace badge with gitlab

- README.md
- asu/api.py
- tests/test_api.py
Now it is possible to directly request a known `request_hash`.
This should be used by all clients to run the verification function of
the server less often. Meaning a client fires the first request,
receives a `reuqest_hash` and can continue polling the hash.
Also usable for front ends to share static links of build images.
> add /api/build/<request_hash> API

- asu/api.py
- asu/build.py
- asu/janitor.py
- tests/conftest.py
- tests/test_build.py
- tests/test_factory.py
Every target comes with specific packages like kmods, which may differ
entirely between targets. It is not enough to estimate packages by
parsing for the x86_64 arch only, but also check for specific packages.
> parse target specific packages

- asu/api.py
- asu/common.py
- tests/test_api.py
Device don't store their profile but a list of supported device. These
are DeviceTree IDs and contain commas instead of underscores. To be
compatible with the ImageBuilder profiles a simple replace if "," to "_"
allows device requests from running devices.
> API: support commas in profile names

- asu/api.py
- asu/common.py
- tests/common_test.py
- tests/test_api.py
Diffing an empty packages list does not make any sense and resulted in
an error with Redis pipeline. Now just ignore those empty packages
lists.
> fixup: an empty packages list causes an error

- asu/api.py
Slow downloads and slow extracting may exceed the 3 minute default
timeout or python rq.
> fixup: set job timeout to 5 minutes

- asu/api.py
Python RQ uses different variable names for the Job() class and the
enqueue function.
> fixup: replace timeout with job_timeout

- asu/janitor.py
I've tried to test ASU with 19.07.2 release (only to find [releases were not yet supported](https://github.com/aparcar/asu/issues/243#issuecomment-605383560) as there are no [JSON files](http://downloads.openwrt.org/releases/19.07.2/targets/?json)) by enabling it in my `~/.local/var/asu-instance/config.py` file:
```py
TESTING=False,
DEBUG=True,
VERSIONS={
"metadata_version": 1,
"branches": [
{
"name": "snapshot",
"enabled": True,
"latest": "snapshot",
"git_branch": "master",
"path": "snapshots",
"pubkey": "RWS1BD5w+adc3j2Hqg9+b66CvLR7NlHbsj7wjNVj0XGt/othDgIAOJS+",
"updates": "dev",
},
{
"name": "19.07",
"enabled": True,
"eol": "2020-01-01",
"latest": "19.07.2",
"git_branch": "openwrt-19.07",
"path": "releases/19.07.2",
"pubkey": "RWT5S53W/rrJY9BiIod3JF04AZ/eU1xDpVOb+rjZzAQBEcoETGx8BXEK", …
```
> Do not try to merge profiles when none were found

- asu/__init__.py
- misc/config.py
- tests/test_build.py
- tests/test_janitor.py
The OpenWrt CDN moved to downloads.cdn.openwrt.org
> fixup: use new OpenWrt CDN

- setup.py
Patrick Decat (2):
Do not try to merge profiles when none were found
Add path information to 19.07 and 18.06 release versions
Paul Spooren (5):
fixup: set job timeout to 5 minutes
fixup: Correct sig_file_headers debug print
fixup: replace timeout with job_timeout
build: adapt to new profiles.json
fixup: use new OpenWrt CDN
> release: v0.4.1

- asu/__init__.py
- asu/api.py
- asu/build.py
- asu/common.py
- misc/config.py
This allows to use define a CA_PUBKEY which is added to running devices. As a consequence a secret upgrade path is possible because OpenWrts `sysupgrade` can check ucert signatures.
> Add ucert support

- asu/api.py
- misc/config.py
- tests/conftest.py
- tests/test_factory.py
Add version to config.py and change branch detection logic to support
rc suffixes.
> add OpenWrt 21.02.0-rc1 support

- README.md
- asu/api.py
- asu/janitor.py
- tests/conftest.py
- tests/test_api.py
While most profiles are unique and there the used target is
"predictable", especially x86 profile names all use "generic". Since it
can't be guaranteed that profiles between targets are unique, require a
specific target.
> api: require target in build request

- .github/workflows/publish.yml
- pyproject.toml
The building and publishing changed with poetry. Reflect that in the
publish CI job and while at it, update the used Docker creation actions.
> CI: improve automatic publishing

- .github/workflows/test.py
By moving from aparcar/ to openwrt/ the CI must be triggered on
`pull_request` and no longer on `push`. While at it improve the
style/naming a little bit.
> CI: test pull requests

- asu/asu.py
- tests/test_build.py
The CDN does not work reliably with snapshot builds as they frequently
change. Disable it for tests, a clean upstream solution should be
implemented where snapshots are stored at a different place than our
release builds.
> meta: don't use OpenWrt CDN

- .github/workflows/publish.yml
Typo in meta job would cause upload of server container to worker image
name. Secondly publishing on tags and releases triggers two jobs at once
which fail since a Pypi package can be only uploaded once.
> CI: fix typo and double publish

- .github/workflows/test.yml
The test file was wrongly renamed to `test.py` instead of `test.yml`.
Test also on pushes to have the CI badge green.
> CI: fix typo of PR test

- docker-compose.yml
If mounting to sub-folders they will be created by Docker and ergo owned
by `root`, which breaks ASU services since they run as regular users.
Also fixup port mismatch between docker-compose and README.
> docker: mount worker to main asu-service/

- asu/build.py
This speeds up the ImageBuilder process since the opkg package manager
doesn't use connection pooling (for encrypted connections). While this
is a speedup it may adds issues caused by unencrypted connects.
> build: Don't downgrade to http

- asu/build.py
- asu/openapi.yml
- tests/test_api.py
The active filesystem was wrongly only set on initial imagebuilder setup
instead of every time an image is build. This was due to the initial
implementation which would disable ext4 in general instead of disabling
filesystems specifically per request.
Now also support JFFS2 and UBIFS filesystems.
> build: reset active filesystem after each build

- asu/build.py
- tests/test_api.py
More tests and mixup typo which broke ext4 handling.
> Improve handling of filesystem parameter

- asu/api.py
- asu/metrics.py
- tests/test_stats.py
Start storing if images are always freshly requested or ever found in
cache. If a image is still building, don't change anything about the
cache since e.g. the firmware selector keeps posting full image requsts
which would increase the cache hits to non-sense.
> stats: store cache hits

- asu/janitor.py
Those packages like nftables are requested by devices but don't exists
as an actual package.
FIXES: https://github.com/openwrt/asu/issues/344
Suggested-by: Justin Klaassen
> handle virtual packages defined in PROVIDES

- asu/janitor.py
The target is relevant, too. Don't store it just for the version.
> cleanup legacy package store based on target only

- asu/api.py
- asu/metrics.py
- asu/openapi.yml
- tests/test_stats.py
This allows to track the clients used to request updates. Ideally this help to
identify what versions are mostly used and drop support for outdated version.
A client can now send the "client" field in the format "name - version".
> api: allow clients to send their identification

- Dockerfile.server
Closes #372 
Signed-off-by: Mitchell Skaggs <skaggsm333@gmail.com>
> Update Python version to 3.10 and use `slim` image

- asu/build.py
The ImageBuilder folder is sometimes deleted without removing it's
stamp, this way the server thinks the folder is still there.
This commit removes stamp, sums ans sig files.
Fix: #377
Future versions should store things in Redis rather than files.
> build: remove IB leftover on cleanup

- asu/api.py
- asu/asu.py
- asu/janitor.py
- asu/templates/overview.html
- tests/test_api.py
- tests/test_factory.py
- tests/test_janitor.py
- tests/test_stats.py
For SNAPSHOTS the targets and architectures likely change over time.
Automatically create the overview file to lower manual maintenance.
> janitor: automatically refresh branches.json

- asu/api.py
- tests/test_api.py
This causes more issues than good. The server must only provide such information and the client should request the user what do to or may "auto default" to what `package_changes` suggest.
Changing this on the server side confuses clients that compare the requested list of packages with the resulting list of packages.
> api: drop server side handling of package_changes

- asu/branches.yml
The revision can be used to "date" package changes so that updates between i.e. snapshots won't be suggested every time.
The mandatory field is used to specify if a changes is selectable or not. If a package is dropped, the changes will always be selected.
Signed-off-by: Paul Spooren <paul.spooren@rhebo.com>
> branches: add revision and mandatory to changes

- asu/asu.py
- misc/asu.service
if the BRANCHES_FILE is set i.e. via service file automatically reload gunicorn. This allows the modification of branches.yml without restarting the service manually.
Signed-off-by: Paul Spooren <paul.spooren@rhebo.com>
> misc: handle BRANCHES_FILE env variable and reload

- asu/build.py
Downstream projects might use different names rather than "openwrt".
> build: use regex instead of hardcoding distribution name

- asu/api.py
- asu/common.py
- tests/test_api.py
- tests/test_common.py
- tests/test_stats.py
If defaults are not allowed but the parameter is supplied, don't error out but instead just ignore it.
Always include the "defaults" content to the request hash, even if empty to avoid an extra case, adjust the corresponding hashes.
If defaults are set, remove the created package after an hour.
> api: better handling of defaults

- asu/janitor.py
The janitor would fail if a branch node contained a date value. As a result, the branches.json, latest.json and overview.json files are never created and therefore acu and/or luci-app-attendedsysupgrade would not be able to update from the asu instance.
Converting json node values to string by default fixes the issue.
This fixes #427 
Signed-off-by: Marc Ahlgrim <marc@onemarcfifty.com>
> fixed release_date in janitor.py

- asu/api.py
- asu/common.py
- tests/test_common.py
When adding a + to the beginning of a package name it will modify the order of packages and thereby fix dependency issues of OPKG.
This is more of a advanced user feature.
> api: allow to prefix packages with a +

- asu/api.py
The new armsr (Arm SystemReady) target provides generic images for Arm platforms with EFI support.
These should be treated similarly to x86 in that the generic images should be used as a base, ignoring the board name.
See also: https://github.com/openwrt/luci/pull/6430
> api: use generic images for armsr target

- asu/build.py
- asu/common.py
Sign images in a separate container after the images is created. This prevents malicious installed packages to steal private keys with post-install scripts.
> sign created images after build

- asu/build.py
- asu/janitor.py
This is overly complicated. Just use a cron script:
cd /mnt/store/ && find . -type d -mtime +10 -exec rm -rf {} \;
> janitor: don't delete old images

- asu/build.py
Broken due to rewording of variables. A testcase should be added.
Fix: #626
> fix package adding with diff_packages: False

- asu/openapi.yml
> openapi.yml: fix "defaults" maxLength documentation

- .github/workflows/test.yml
- Containerfile
- README.md
- asu/api.py
- asu/asu.py
- asu/branches.yml
- asu/build.py
- asu/common.py
- asu/janitor.py
- asu/openapi.yml
- misc/config.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_common.py
- tests/test_janitor.py
- tests/test_package_changes.py
- tests/test_stats.py
this call can be called by a remote process to trigger an update of a specific version/target combination, instead of requestion *everything* all the time. This should be a massive performance improvement and keep things better in sync.
If you enable UPDATE_TOKEN, the janitor process won't run every x minutes anymore.
For openwrt.org, this can be called via buildbots, for other projects this could be called via webhooks from just about any CI.
> api: add /update/<version>/<target> call

- asu/api.py
- asu/asu.py
- asu/build.py
- misc/config.py
Downstream project may use different images or container registries.
> config: add BASE_CONTAINER option

- asu/asu.py
- misc/config.py
Current value of 100 is less than default when building OpenWrt (104). Increase it to 1024 to allow large root file systems on devices that can accommodate them.
https://github.com/openwrt/openwrt/blob/61e8728d86d7c11e1a5adab4bd37dae6b3b6cf2b/config/Config-images.in#L306
Closes: https://github.com/openwrt/asu/issues/826
> build: increase MAX_CUSTOM_ROOTFS_SIZE_MB to a reasonable value

- asu/openapi.yml
- asu/update.py
Add site-configurable upstream URL to 'overview' api, per our discussion at https://github.com/efahl/owut/issues/2.
> api: add upstream_url to overview

- asu/build.py
Image type "sdcard" was missing from checks, so those images were not being signed.  Example platform is compulab_trimslice tegra/generic.
Snippet from build manifest, with ignored "type".
```
"images": [
{
"filesystem": "squashfs",
"name": "openwrt-415d38074a1b-tegra-generic-compulab_trimslice-squashfs-sdcard.img.gz",
"sha256": "59ebfc597eb6e8fb1fb1b2bf781474fb7ee468ccad17b811d75f4d99c32e0100",
"sha256_unsigned": "75543310f059f106c07d9691ab79b79021778488098b7c63b572ed85d0bb3c34",
"type": "sdcard"
},
```
> build: add missing image type

- asu/branches.yml
'auc' has been removed and replaced by 'owut', reflect that in the 'package_changes'
https://github.com/openwrt/packages/commit/3a998e10218c318511b41739f276e572c1ede967
> config: add entry to package_changes

- tests/test_api.py
The hash changed due to the FastAPI rewrite where `distro` is no longer empty but defaults to `openwrt`
> tests: fix changed hash

- asu/config.py
- asu/routers/api.py
Use pydantic's Field to add constraints to 'defaults' (string length <= 20480) and 'rootfs_size_mb' (int 1 <= value <= 1024) 'package_changes'
Reference:
https://docs.pydantic.dev/latest/concepts/fields/#numeric-constraints
Signed-off-by: Eric Fahlgren @efahl
> routers/api: add constraints to API fields

- asu/routers/api.py
Replace FastAPI 'ModelBase.dict' method with 'ModelBase.model_dump' to eliminate deprecation warnings.
> api: fix deprecation warnings

- asu/build.py
- asu/routers/api.py
- tests/test_api.py
Restore the 'version_code' field as it's used by both auc and owut to verify the resulting build.
> api: restore 'version_code' for auc and owut

- asu/build.py
- asu/routers/api.py
- asu/util.py
- tests/test_api.py
- tests/test_util.py
This allows users to work around an opkg bug that causes package installation failure when the package list is sorted.  For one specific example, see https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035/61.
- Firmware selector needs to have its sort removed.
https://github.com/openwrt/firmware-selector-openwrt-org/blob/master/www/index.js#L618
- I already updated owut. https://github.com/efahl/owut/commit/d8af324ccad0c93f0d6a9fd1e72236e55d480a7c
- Haven't looked at LuCI ASU yet.
> build: retain user input order in package list

- tests/test_api.py
Test the values and defaults produced by a minimal build request.
> test_api: add test for all values in build request API

- asu/util.py
- tests/test_util.py
Fixes the common Python 'strip bug' in extracting versions and names from
base strings.
Example input:
Package: libusb-1.0-0
ABIVersion: -0
```
old: "libusb-1.0-0".rstrip("-0")       -> "libusb-1."
new: "libusb-1.0-0".removesuffix("-0") -> "libusb-1.0"
```
> util: use 'removesuffix' when removing trailing substrings

- tests/test_api.py
Add test cases with both diff_packages true and false, with the input package list both unordered and sorted.  Request hash must be identical regardless of package list order.
> test_api: verify request hash with different package ordering

- asu/main.py
This was an issue in the past where people would set the upgrade server URL to something with a trailing slash, resulting requests containing a duplicate slash.
Redirect double slashes to single slashes to solve the issue.
> api: redirect double slashes

- README.md
My VM gave me user id 1000, which caused some confusion when I first tried to get the server up.  Fix the instructions to use 'id -u', so users don't have to figure it out.
> readme: fix bug in roll-your-own setup instructions

- asu/update.py
- tests/test_api.py
Add some logic to gracefully ignore updates on old versions that lack the proper data to be supported.
Every time I did a cold start, I'd get a bunch of errors on the worker:
```
File "/app/asu/update.py", line 26, in update_targets
version_path = branch_data["path"].format(version=version)
^^^^^^
KeyError: branch_data has no key "path"
```
Stuck an assertion in and turns out to be the `19.07` stuff,
```
AssertionError: No path for 19.07.7
```
Not sure if it happens in production, but this fixes it and cleans up a few little things.
> asu/update: avoid crashes on non-existent or obsolete versions

- asu/main.py
- asu/routers/api.py
- asu/update.py
- asu/util.py
Let redis do the bytes to utf-8 conversions automatically, cleaning up the asu code.  Also fixes creation of overview.html template, which has been broken for a while.
- enable automatic decoding on creation of redis client
- remove all 'decode' calls on returned objects
- sort branch and version lists making comparisons when debugging easier
> asu: eliminate use of redis bytes data

- asu/build.py
- asu/util.py
- poetry.lock
- pyproject.toml
- tests/test_util.py
- tests/upstream/snapshots/targets/testtarget/testsubtarget/openwrt-imagebuilder-testtarget-testsubtarget.Linux-x86_64/Dockerfile
Since upstream implemented `dmux` for exec_run it should be used instead of creating containers multiple times. Previously it wasn't possible to tell stderr apart from stdout, making it harder to parse things. Now with proper demuxing, recycle the container all three times, yey!
> build: use exec_run with dmux

- asu/util.py
- tests/test_util.py
Occasionally, upstream package files are being terminated with extra newlines, resulting in '"null": null' entries in the resulting package index.  Strip the input text to avoid this.
Change the splitting method on the text to both reduce memory footprint and speed things up.
I reported this back in https://github.com/openwrt/asu/issues/866, but it was transient and I never got to the bottom of it.  Fixed now.
> util: improve package file parsing

- asu/routers/api.py
- tests/conftest.py
- tests/test_api.py
Replace special casing for x86 and armsr with more algorithmic approach. Fixes bug with x86/geode, which was silently transforming 'geos' profile into 'generic'.  Handles other generic platforms without code changes.
Also did general cleanup/refactoring of build validation error handling, and added more build validation test cases.
> api: clean up handling of mapped_profiles

- .gitignore
Once I started using squid, ruff was complaining about "read only" for all the cache dirs.
> git: ignore the squid cache directory

- asu/build.py
- tests/conftest.py
A re-do to use the proper mechanism for determining actual upstream path, using upstream-provided data.
I had forgotten about this until I was fixing something in owut and saw the branches.path, "Oh, right!"
> build: pass in correct VERSION_PATH for release snapshots

- asu/util.py
Set the gid:uid on the tar file members as we extract them from the build archive, so they are owned by a real user in both the container and on the host.
This came about from two things: part of documenting setup of a local server, and attempting to write host-based tools to manage build storage.
> util: set group:user on extracted tar members

- asu/build_request.py
Add full annotations to all BuildRequest members, including the verbose descriptions from the pre-pydantic API.  This produces much better documentation in the redoc and api docs.  Also did a little semantic reordering, so the flow of the docs is a bit better.
> chore: improve typing and annotations on BuildRequest

- pyproject.toml
Add a config entry to constrain pytest's search for test files and functions to only the 'tests/' directory.  This avoids error messages about read-only subdirectories, like you get when running squid.
> tests: add config to scan only tests directory

- asu/build.py
- asu/routers/api.py
- asu/util.py
- tests/test_api.py
Ensure that 'imagebuilder_status' is reported at all phases of build, and add a final "done" status.
Ensure that all GET and HEAD requests to '/build' receive all x-headers regardless of build phase.
After reading through all the FastAPI docs, it turns out you can put '@get' and '@head' on the same function and it works just as you would expect.  Reduces code size a bit.
Extended the 'build_get' test to also include the HEAD request and confirm that sequential HEAD and GET requests receive the same data.
> builder: add more consistency and finer granularity to build status

- asu/routers/api.py
- asu/util.py
More chipping away at full typing.  Extract and add type to "magic number" from hash calculations.
> chore: more typing

- asu/config.py
Add an entry into 'package_changes' to handle the renaming of the LuCI package manager app.
> package-changes: luci-app-opkg renamed luci-app-package-manager

- asu/main.py
- asu/util.py
As of the apk switchover, the Packages file no longer is created as part of the package feeds.  Instead, utilize the index.json file created from apk's packages.db.
See https://github.com/openwrt/openwrt/commit/f841870
> util: read index.json for snapshot package feeds

- asu/config.py
Consolidate all the package changes into a single table. Factor all relevant release info into a single function.
Adds the 24.10 release and cleans up the addition of new releases, and new package changes.
> config: refactor adding new releases

- asu/config.py
Allow 24.10 and earlier builds to transition their package manager transparently when they move to snapshots or post-24.10 releases.
Not a real high priority, but fixes a workaround in owut.  Probably makes life easier for LuCI app, too.  I waited for some clarity on how 24.10 was going to proceed, so this looks safe now.
> config: add the opkg -> apk-mbedtls package change

- asu/main.py
- asu/util.py
- tests/test_util.py
The builds for 23.05-SNAPSHOT and 23.05.6-and-later also need to be included in the kmod-split handling.
See discussion on the buildbot commit for details: openwrt/buildbot@a75ce026
> util: collect separate kmods index depending on version

- asu/build.py
- asu/util.py
- tests/test_util.py
Properly detect versions for which the slim imagebuilder containers using setup.sh is being used.  Set up the container accordingly.
Allows building the new 24.10 versions, including the RCs.
> build: use new imagebuilder setup.sh for appropriate versions

- .github/workflows/publish.yml
Instead of cloning the repository again, use the local context with the modified __version__.
> ci: use correct context for docker build action

- asu/update.py
The LuCI Attended Sysupgrade app uses the 'latest' list in overview.json to determine versions shown to the end user.  It currently does not show the 'upcoming_version', which means users don't see the 24.10.0-rc series.
If 'upcoming_version' exists, then let's add it to that list, so users can test out the RCs.
Fixes: https://github.com/openwrt/openwrt/issues/17595
> update: include any upcoming version in latest release list

- asu/build.py
When two builds are submitted for the same target/version and both include uci-defaults, then the second build fails with
FileExistsError: [Errno 17] File exists: '.../files/etc/uci-defaults'
Links: https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035/394
> build: don't crash if uci-defaults directory already exists

- asu/build.py
- asu/package_changes.py
- tests/test_package_changes.py
Utilize the 'apply_package_changes' mechanism to apply algorithmic replacement of language packages that have changed names at a major release boundary.
Also fixed the long-standing typo: 'appy' -> 'apply'
Links: https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035/406
> build: do auto-replacement on language packages that have been renamed

- asu/config.py
'luci-app-diag-core' was removed from the package feeds, include it in the 'package_changes' list.
Fixes: #1185
> config: add removed package to package_changes

- asu/build.py
Allow to "downgrade" HTTPS connections to be cached by squid. In both cases, packages indexes are verified by OPKG keys (usign) or APK itself.
Related: https://github.com/openwrt/asu/pull/1187
> feat: add cache to packages

- asu/package_changes.py
The cleaner implementation is to handle this on the clients. @efahl do you work on the LuCI app? If not we should consider dropping it or find someone else to maintain it.
> fix: replace `auc` with `owut` for 24.10 releases

- asu/package_changes.py
- tests/test_package_changes.py
Fix a bug in language packages name updates when the language identifier contains a dash.  Examples are "zn-ch" or "zh-hant".
Reported-by: @1715173329
Links: https://github.com/openwrt/asu/pull/1155#discussion_r1947690063
> build: apply-package-changes: handle long language identifiers

- asu/build.py
This is a minor fix that removes failed containers, before the report_error function, to free up what little space they would occupy in ram until the timeout.
> fix: remove the container once it has failed

- .github/workflows/test.yml
Things happen in containers these days
> chore(ci): don't install libncurses5-dev anymore

- misc/squid.conf
If not, we may have a missmatch between the package index and the individual files.
> feat(squid): always refresh cache

- .github/workflows/podman.yml
- .github/workflows/test.yml
- README.md
- asu/config.py
- asu/util.py
- misc/asu.env
- podman-compose.yml
Based on the work of @efahl with a bunch of simplifications.
* Drop `CONTAINER_SOCK` and `CONTAINER_HOST` in favour of `CONTAINER_SOCKET_PATH`.
* Install dependencies directly instead of using `pip`.
* Mention Podman socket via `systemd` or `podman service`
* Drop `asu.env`, there are no good defaults since variables are not evaluated, the Podman socket path varies etc.
* Drop outdated screenshot of `auc`.
* Some guidance on Squid cache setup.
Supersedes #1032
> docs(self-hosted): document and simplify setup

- asu/main.py
- asu/util.py
There were two code paths reading .versions.json, the first of which, in main:generate_latest, would update the cache version appropriately, but then when utils:reload_versions was called, it would see from_cache was true and never update its internal data structures.  The code paths were consolidated, so there is only one touch point for the .versions.json file now, eliminating the race.
Likewise, the version/target/profiles.json files are being read on many paths, but util:reload_profiles was basing its decision to update on the same flawed from_cache check.  Eliminating the cache check altogether seemed most appropriate here, as there's no easy way to consolidated the various uses of the profile.json file into a single point of contact.
> utils: eliminate cache races for .versions.json and profiles.json

- asu/config.py
We somehow got a duplicate entry for the libustream change in the table, remove it.
> config: remove redundant entry in package_changes

- asu/util.py
In newer python podman versions, the exec_run method may return None as a value for either of stdout or stderr when there is no output, where they previously always returned an empty bytestring. This raises an AttributeError when it occurs cascading into an "Internal server error", fix it by checking before decoding the bytestrings.
@aparcar:
This bug fix should be applied before doing any Python package upgrades on the production servers.
> util: handle None returned as output string

- asu/build.py
The logged build duration was being computed using the creation date stamp for the imagebuilder.  This resulted in values being many millions of seconds for release images.  Change it to compute the actual real time spent performing the build.
> stats: compute a reasonable value for build duration

- asu/routers/api.py
The cache-hits statistics were being logged for both HEAD and GET requests, which incorrectly doubled the apparent number of hits.  Cache hits only count on a real GET request, so we now ignore all HEADs when gathering statistics.
> stats: only log legitimate cache hits

- misc/squid.conf
Mention most applicable parameters sizing squid cache
Tailored to 24.10.0 content Largest package 91MB, average 400KB median 120KB
Oversize packages of near future or full SDK will not affect memory cache efficiency by going directly to the disk
Can apply to current populated cache with -k reconfigure without restart
Signed-off-by: Andris PE <neandris@gmail.com>
> Fine-tune squid parameters

- asu/routers/stats.py
- asu/util.py
When two build requests arrive at the same time (within one second of each other), adding the timestamp of the second request would fail and abort the build with the client seeing "500 Internal server error".
asu_server_1   File "/app/asu/routers/api.py", line 223, in api_v1_build_post
asu_server_1     add_timestamp(
asu_server_1   File "/app/asu/util.py", line 47, in add_timestamp
asu_server_1     get_redis_client().ts().add(
...
asu_server_1 redis.exceptions.ResponseError: TSDB: Error at upsert, update is not supported when DUPLICATE_POLICY is set to BLOCK mode
The timeseries "add" call has a default value of "block" for duplicate timestamps.  We change it to "sum", so that arbitrarily many requests can arrive at the same time without issue and we also accumulate proper statistics.
> stats: accumulate results at same timestep

- asu/util.py
On rare occasion the download of .versions.json fails with a 404, probably due to requesting it while it's being updated.  If this happens during a build request, it causes an "Internal server error" and the job request fails.  Fix that by simply not updating the internal versions list and continuing on until the versions are available.
> util: handle missing .versions.json gracefully

- asu/build.py
- tests/test_api.py
If a container image is missing for whatever reason, then the image pull raises an exception:
ImageNotFound: 404 Client Error: Not Found ({"message":"manifest unknown"}
This is propagated to the ASU clients as a "status 500 - Internal server error".  The ASU clients then simply report "init" as an error with no supporting details, leaving the user completely in the dark as to what is going on.
We add an error handler around the image pull, so now the server reports very specific details about the failure, helping diagnose the issue:
RuntimeError: Image not found: ghcr.io/openwrt/imagebuilder:lantiq-xrx200-v24.10.1
Link: https://forum.openwrt.org/t/luci-attended-sysupgrade-support-thread/230552/68
> build: handle errors during container download

- asu/build.py
- tests/test_api.py
Fix both format and test errors caused by new message text, which cause CI checks to fail.
Ref: https://github.com/openwrt/asu/commit/6fe616bb7708554f4143b1b6c5994d9c95be269c
> build: reformat recent changes and fix test

- asu/main.py
- asu/templates/overview.html
Add both the rootfs partition max size and uci-defaults scripts max length to the overview's server section, allowing clients to validate them prior to submitting an invalid request.  Display the uci-defaults size on the front page, if applicable.
> api: expose internal server limits in overview

- tests/conftest.py
- tests/test_stats.py
Some of the test_stats tests would fail occasionally with the wrong queue length.  Traced it back to the redis 'Queue' object somehow persisting across tests.  We now ensure that a fresh queue is used for each test.
> tests: fix spurious failure of stats tests

- asu/util.py
During the creation of a new maintenance release, it is possible that the new version's .target.json file has not yet been created. This causes a "500 internal server" error for all users, even if they request a different version.  Rather than crash attempting to decode the 404 html code as json, we simply return an empty dictionary.
This results in users seeing the "Unsupported target" message if they try to build the new version, but that's better than crashing for everyone.
> util: handle missing .targets.json file
