openwrt/asu

update-server/tables.sql

complete default_packages view and introduce ON INSERT rule.
in mysql this will have to be done using [`CREATE TRIGGER`](https://dev.mysql.com/doc/refman/5.7/en/trigger-syntax.html)

view and insert rule example for postgresql

---

worker.py

there will be many errors, so at least present them nicely

log stderr and pretty print

---

server/build_request.py
utils/tables.sql

add build_position again

---

utils/config.yml.default
utils/database.py
worker.py

enable multi thread builders and updaters
this is nice as the package update is quite slow, now we can 8 in parallel

Fast update

---

utils/database.py
utils/image.py
utils/tables.sql
worker.py

store build_seconds and show them in the overview of popular targets

store build_seconds

---

README.md
asu/request.py
asu/upgrade_check.py
asu/utils/config.py
asu/utils/tables.sql

This isn't really schwifty as it removes the ability to perform in release upgrades, but fixes the thing for now, inb4 18.06.2...

Simple upgrade check

---

asu/utils/image.py

This should confuse people less

Reset buildlog on rebuild instead of appending

---

.gitlab-ci.yml

backport automated tests

---

.gitlab-ci.yml

Also run tests on master and tag image

---

contrib/nginx-asu-server.conf

This should allow tools like chef and luci to access the files.

apply cors nginx config from enable-cors.org

---

asu/api.py

This would result in an infinite queue to job adding.

fixup: wrong indention in asu/api.py

---

.github/workflows/pythonapp.yml
asu/__init__.py
asu/api.py
asu/build.py
asu/janitor.py
docs/reference/common.md
tests/conftest.py
tests/test_api.py
tests/test_build.py

This format is inspired by the current discussion on openwrt-devel[0].
This should ideally allow clients (LuCI/cli) to check for updates and
either download them directly from the upstream server request images
from ASU.
Also added some documentation and updated the tests.
[0]: https://lists.infradead.org/pipermail/openwrt-devel/2020-March/021970.html

Implement branch system for versions

---

.github/workflows/pythonapp.yml

actions: use Codecov

---

tests/test_janitor.py
tests/upstream/snapshots/packages/x86_64/base/Packages
tests/upstream/snapshots/targets/?json
tests/upstream/snapshots/targets/testtarget/testsubtarget/openwrt-testtarget-testsubtarget-testprofile.json
tests/upstream/snapshots/targets/testtarget/testsubtarget/packages/Packages

tests: add janitor tests

---

README.md

README: actually add Codecov button

---

README.md

README: add black badge

---

README.md
setup.py

Important commits:
5b08a64 Add manifest to build response
4e8bc46 add GitHub actions
5c743d2 Create LICENSE
1737414 Add initial documentation via `mkdocs`
9da1e94 Implement branch system for versions
595a412 fixup: empty package list and diff_packages name
afcfb4b build: implement `diff_packages`

release: v0.4.0

---

asu/build.py

fixup: Correct sig_file_headers debug print

---

asu/build.py
asu/janitor.py
misc/config.py

This allows to handle external projects like LibreMesh.

add extra_repo option

---

asu/api.py
asu/build.py
asu/common.py
tests/test_api.py
tests/test_common.py

Both functions are described in the README.

api: add `version_code` and `packages_versions`

---

README.md
asu/api.py

This should help the users to help estimate how long their build takes.

api: return queue_position

---

README.md
asu/api.py
asu/asu.py
asu/openapi.yml
dev-requirements.txt
misc/config.py
requirements.in
requirements.txt
setup.py
tests/test_api.py

Using connexion allows to use OpenAPI definitions to design the API and
automatically validate parts of it. This should improve testing and
documentation at once.

asu: switch to connexion

---

asu/api.py
asu/build.py
asu/openapi.yml
requirements.in
requirements.txt
tests/test_build.py

these stages are updated within a job and should improve the user
experience when waiting for updates.

build: add stages

---

asu/api.py
asu/asu.py
asu/build.py
asu/common.py
asu/openapi.yml

support uci-defaults parameter

---

asu/asu.py
asu/janitor.py
asu/templates/overview.html
setup.py

Add simple overview to the server

---

asu/janitor.py

This seem to cause context issues with flask and may get the server
banned due to rate limits, just do updates in a for loop.

janitor: don't use pool for updates

---

asu/api.py

Within OpenWrt the profile does not always matches the `board_name`,
which is determined via device tree files. As a workaround ASU
automatically parsed the "supported" devices and mapped incomming
requests to profiles. In some rare cases (#319) the support profile is
actually a different profile than the one installed, in this case a
device that support images with and without nand storage.
To fix this, first check if a profile with the device tree model exists
(by replacing `,` with `_`) and only use the *supported mapping* if it
does not.
Fixes: #319

api: prefer profile directly over mapped one

---

README.md
docker-compose.yml
misc/Caddyfile

And also make it compatible with podman-compose.

docker: simplify docker-compose

---

.github/workflows/publish.yml

This makes tagging much more complex but why not.

CI: use latest Docker build-and-push action

---

asu/build.py

The urllib currently fails on macOS with encrypted connections, replace
it with `requests` since it's used everywhere else anyway.

build: replace urllib with requests

---

asu/api.py
asu/build.py
asu/metrics.py
tests/test_stats.py

Store how may non default packages were installed. While at it run code
linter and clean some dead code.

stats: add extra package installs

---

.github/workflows/test.yml
asu/janitor.py

Always adding results in never deleting old packages.

janitor: replace sets instead of just adding

---

README.md
misc/worker@.service

You may want to run more than one worker

misc: service example for multiple workers

---

asu/build.py

Instead of running an external service remove outdated ImageBuidlers
after every build. This could be improved by only checking this once a
day or so but for now it should fix storage issues where ImageBuidlers
pile up forever.

build: automatically remove unused ImageBuilders

---

.gitignore

Signed-off-by: Paul Spooren <paul.spooren@rhebo.com>

gitignore: add venv

---

asu/branches.yml

Add new service releases.
Signed-off-by: Alex Taran <oleksii.taran@gmail.com>

branches: add 22.03.2 and 21.02.5

---

asu/branches.yml

branches: replace procd-ujail-console with uxc

---

asu/branches.yml
asu/build.py
asu/common.py
asu/janitor.py

Ideally break less devices during user updates

workarounds for next release

---

asu/branches.yml

Add 23.05.0 stable release

---

asu/build.py
asu/package_changes.py
tests/test_package_changes.py

This file allows to modify package changes based on release, target and
version. At some point it could become a YAML file but works for now.

add package_changes.py

---

asu/branches.yml

I did not bump the date - is that expected? The documentation is not clear what it is used for, or supposed to be used for.

branches: add 23.05.2

---

asu/common.py

The stuff would be written, however not flushed and causing tar operation to fail.

build: add missing flush()

---

asu/common.py

common: cleanup unused get_targets function

---

tests/test_api.py

Add tests for 'defaults' too long and 'rootfs_size_mb' out of range.

tests/api: add test cases for constrained fields

---

asu/main.py

Replace the deprecated 'on_event' hook with the current 'lifespan' context manager.  Eliminates warnings during run and tests.

main: rework deprecated 'on_event' use

---

.github/workflows/publish.yml
.github/workflows/test.yml

The current images would use podman 3.x

ci: use ubuntu-24.04 for more recent podman verison

---

poetry.lock
pyproject.toml

Now that timeseries testing is possible, use it.

poetry: use official fakeredis release

---

pyproject.toml
tests/conftest.py
tests/test_api.py
tests/test_util.py

Add tests for missing functions with better response checking. Add context output for html report.
New reporting context looks like this, lets you see what tests hit what line.

tests: improve coverage and reporting

---

asu/util.py

Reduce footprint and clean up the feeds and package file parsers.
Just make some stuff more pythonic and reduce the code size.

util: clean up package file parsing

---

asu/util.py

Consolidate all util output into worker log.  Suppress the duplicate log messages to make output more readable.

logging: clean up utility function logging

---

asu/build.py
asu/build_request.py
asu/main.py
asu/util.py
tests/test_api.py
tests/test_util.py

remove some unecessary conditions, use OpenWrt One as default example, run isort, bettern patterns for fields

chore: cleanups and OpenWrt One as default

---

asu/build_request.py

Some versions may contain a tilde, allow it.

build_request: allow tilde in version

---

asu/update.py

overview: add upcoming versions

---

asu/util.py
tests/test_util.py

Remove the hacky 'snapshot' version detection code, so that all versions are handled consistently (avoids breakage on the next stable release).  Optimize the creation of the package list by utilizing any existing upstream index.json if it is available and of the correct format.
---
This works fine right now without any upstream changes, but will start working best after https://github.com/openwrt/openwrt/pull/19051 has been merged and the builds pick it up.

util: improve package index generation

---

asu/routers/api.py

When internal errors are generated during build processing, the error message is sometimes saved in the 'response.error' field instead of 'response.stderr'.  This causes Firmware Selector to leave out crucial reporting information, as it is expecting errors in the stderr response field.
Also, when errors occur during container startup, the 'response.detail' is often left containing "init", making the errors reported to the user even more confusing.
Fix this by
1) Eliminating the 'error' field altogether, always return the
messages in 'response.stderr';
2) Set the 'response.detail' field to "failed" when detail is set to
"init" and an internal error is detected.
Fixes: https://github.com/openwrt/firmware-selector-openwrt-org/issues/99

api: return error info in proper fields

---

README.md

Hello! I've been running this server for a couple of months, so far no issues and has worked fine for me. Sending a pr to add it to the list.

docs: add server sysupgrade.guerra24.net
